# Azure Pipelines CI build configuration
# Documentation at https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
    - 'master'
  tags:
    include:
    - '*'
pr:
  branches:
    include:
    - '*'

jobs:
- job: "Toolchains_RV32IMC"
  displayName: "Toolchains targeting Ibex"
  pool:
    vmImage: "ubuntu-20.04"
  container: centos:6
  timeoutInMinutes: 360
  steps:
  - template: "_build-deps.yml"

  - bash: |
      ./prepare-centos6.sh
    displayName: Install build prerequisites on CentOS6

  - bash: |
      ./build-gcc-with-args.sh \
        "lowrisc-toolchain-gcc-rv32imc" \
        "riscv32-unknown-elf" \
        "/tools/riscv" \
        "-march=rv32imc" "-mabi=ilp32" "-mcmodel=medany"
    displayName: 'Build GCC toolchain'
    env:
      ARTIFACT_STAGING_DIR: $(Build.ArtifactStagingDirectory)
      RELEASE_TAG: $(ReleaseTag)

  - bash: |
      ./build-clang-with-args.sh \
        "lowrisc-toolchain-rv32imc" \
        "riscv32-unknown-elf" \
        "/tools/riscv" \
        "-march=rv32imc" "-mabi=ilp32" "-mcmodel=medany"
    displayName: "Build Clang toolchain"
    env:
      ARTIFACT_STAGING_DIR: $(Build.ArtifactStagingDirectory)
      RELEASE_TAG: $(ReleaseTag)

  - template: "_upload-artifacts.yml"
    parameters:
      azure_name: rv32imc-toolchains
